# -*- coding: utf-8 -*-
"""Machine Learning Project(Final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3Ks9MzPFEZRkermQZJCg8zwedJiRehy

**Machine Learning**  
**Sonar Signal-Based detection of Rocks and Mines using Machine Learning**

Importing Dependencies
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

"""Data Collection and Processing"""

# loading dataset
sonar_data=pd.read_csv('/content/sonar data.csv',header=None)
print("Dataset loaded successfully")
sonar_data.head() #displaying first 5 rows data

#describe (statistical measures of data)
sonar_data.describe()

# No.of rows and columns
sonar_data.shape

# class distribution
sonar_data[60].value_counts()

"""M --> Mine

R --> Rock
"""

sonar_data.groupby(60).mean()

# separating data features and Labels
X = sonar_data.drop(columns=60, axis=1)
Y = sonar_data[60]
print(X)
print(Y)

"""Training and Test data"""

x_train,x_test,y_train,y_test=train_test_split(
    X,Y,test_size=0.1,random_state=42,stratify=Y
)
print(X.shape, x_train.shape, x_test.shape)

print(x_train)
print(y_train)

# Feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

"""Models Training"""

# Logistic Regression

lr_model = LogisticRegression()
lr_model.fit(x_train, y_train)

#accuracy on train data
lr_train_prediction = lr_model.predict(x_train)
lr_train_accuracy = accuracy_score(y_train, lr_train_prediction)
print(' Train accuracy of Logistic regression: ', lr_train_accuracy)

#accuracy on test data
lr_prediction = lr_model.predict(x_test)
lr_accuracy = accuracy_score(y_test, lr_prediction)
print(' Test accuracy of Logistic regression: ', lr_accuracy)

print("Logistic Regression Classification Report:\n")
print(classification_report(y_test, lr_prediction))

# Naive bayes

nb_model=GaussianNB()
nb_model.fit(x_train,y_train)

#accuracy on train data
nb_train_prediction = nb_model.predict(x_train)
nb_train_accuracy = accuracy_score(y_train, nb_train_prediction)
print('Train accuracy of naive bayes: ', nb_train_accuracy)

#accuracy on test data
nb_prediction = nb_model.predict(x_test)
nb_accuracy = accuracy_score(y_test, nb_prediction)
print('Test accuracy on test data : ',nb_accuracy)

print("Naive Bayes Classification Report:\n")
print(classification_report(y_test, nb_prediction))

# Random forest regression

rf_model= RandomForestClassifier(
    n_estimators=100,
    max_depth=3,
    min_samples_split=10,
    min_samples_leaf=4,
    max_features='sqrt',
    random_state=42
)
rf_model.fit(x_train,y_train)

rf_train_prediction = rf_model.predict(x_train)
rf_train_accuracy = accuracy_score(y_train, rf_train_prediction)
print('Train accuracy of random forest : ', rf_train_accuracy)

rf_prediction = rf_model.predict(x_test)
rf_accuracy = accuracy_score(y_test, rf_prediction)
print('Test accuracy of random forest: ', rf_accuracy)

print("Random Forest Classification Report:\n")
print(classification_report(y_test, rf_prediction))

# Support Vector Classification

svc_model=SVC(
    kernel='rbf',
    C=1,
    gamma='scale'

)
svc_model.fit(x_train,y_train)

svc_train_prediction = svc_model.predict(x_train)
svc_train_accuracy = accuracy_score(y_train, svc_train_prediction)
print('Train accuracy of svc: ', svc_train_accuracy)

svc_prediction = svc_model.predict(x_test)
svc_accuracy = accuracy_score(y_test, svc_prediction)
print('Test accuracy of svc: ', svc_accuracy)


print("Support Vector Classification Report:\n")
print(classification_report(y_test, svc_prediction))

# knn

knn_model=KNeighborsClassifier(
    n_neighbors=5
    )
knn_model.fit(x_train,y_train)

knn_train_prediction = knn_model.predict(x_train)
knn_train_accuracy = accuracy_score(y_train, knn_train_prediction)
print('Train accuracy of knn: ', knn_train_accuracy)

knn_prediction = knn_model.predict(x_test)
knn_accuracy = accuracy_score(y_test, knn_prediction)
print('Test accuracy of knn : ', knn_accuracy)

print("KNN Classification Report:\n")
print(classification_report(y_test, knn_prediction))

# Cross Validation scores
models = {
    'Logistic Regression': lr_model,
    'Naive B': nb_model,
    'Random Forest': rf_model,
    'SVC': svc_model,
    'KNN': knn_model
}

for name, model in models.items():

    scores = cross_val_score(model, x_train, y_train, cv=5)

    print(name)

    print("Cross Validation Accuracy:", scores.mean())

    print()

"""Exploratory Data Analysis"""

#Model Comparison
models = ['Logistic Reg','Naive B', 'Random Forest', 'SVC', 'KNN']
train_accuracies = [lr_train_accuracy, nb_train_accuracy, rf_train_accuracy, svc_train_accuracy, knn_train_accuracy]
test_accuracies = [lr_accuracy, nb_accuracy, rf_accuracy, svc_accuracy, knn_accuracy]
x = np.arange(len(models))
width = 0.35

plt.bar(x - width/2, train_accuracies, width, label='Training Accuracy', color='skyblue')
plt.bar(x + width/2, test_accuracies, width, label='Test Accuracy', color='lightcoral')
plt.xticks(x, models)
plt.xlabel("Models")
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.show()

results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Naive B',
        'Random Forest',
        'SVC',
        'KNN'
    ],

    'Accuracy': [
        lr_accuracy,
        nb_accuracy,
        rf_accuracy,
        svc_accuracy,
        knn_accuracy
    ]
})

print(results)

#Class Distribution
plt.figure()
sonar_data[60].value_counts().plot(kind='bar')
plt.title("Class Distribution (Rock vs Mine)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

#Mean Sonar Signal Across Features
plt.figure()
X.mean().plot()
plt.title("Mean Sonar Signal Across Features")
plt.xlabel("Feature Index")
plt.ylabel("Mean Value")
plt.show()

#Rock vs Mine
plt.figure()
rock = sonar_data[sonar_data[60] == 'R'].iloc[0, :-1]
mine = sonar_data[sonar_data[60] == 'M'].iloc[0, :-1]

plt.plot(rock.values, label="Rock")
plt.plot(mine.values, label="Mine")
plt.title("Example Sonar Signal: Rock vs Mine")
plt.xlabel("Feature Index")
plt.ylabel("Signal Strength")
plt.legend()
plt.show()

#Confusion Matrix
from sklearn.metrics import confusion_matrix
svc_prediction = svc_model.predict(x_test)


cm = confusion_matrix(y_test, svc_prediction, labels=['R', 'M'])

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Rock (R)', 'Mine (M)'],
            yticklabels=['Rock (R)', 'Mine (M)'])

plt.title('Confusion Matrix: SVC Sonar Classification')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.show()

#Conclusion
#Among all machine learning algorithms tested,
#Logistic Regression demonstrated stable and reliable
#performance for sonar signal classification.

#Although some models achieved slightly higher accuracy,
#Logistic Regression was selected due to its simplicity,
#interpretability, and effective generalization capability.

"""**Predictive system**"""

input_data = (0.0307,0.0523,0.0653,0.0521,0.0611,0.0577,0.0665,0.0664,0.1460,0.2792,0.3877,0.4992,0.4981,0.4972,0.5607,0.7339,0.8230,0.9173,0.9975,0.9911,0.8240,0.6498,0.5980,0.4862,0.3150,0.1543,0.0989,0.0284,0.1008,0.2636,0.2694,0.2930,0.2925,0.3998,0.3660,0.3172,0.4609,0.4374,0.1820,0.3376,0.6202,0.4448,0.1863,0.1420,0.0589,0.0576,0.0672,0.0269,0.0245,0.0190,0.0063,0.0321,0.0189,0.0137,0.0277,0.0152,0.0052,0.0121,0.0124,0.0055)

# changing the input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the np array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = lr_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
  print('The object is a Rock')
else:
  print('The object is a mine')